# General settings
# ----------------------------------------------------------------------------
tick_rate = 50
default_channel = "files"
history_size = 200
global_history = false

[ui]
# How much space to allocate for the UI (in percentage of the screen)
ui_scale = 100
# What orientation should tv be (landscape or portrait)
orientation = "landscape"
theme = "catppuccin-mocha-mauve"

[ui.input_bar]
position = "bottom"
prompt = ">"
# header = "{}"
# padding = {"left": 0, "right": 0, "top": 0, "bottom": 0}
border_type = "rounded"

[ui.status_bar]
separator_open = ""
separator_close = ""
hidden = false

[ui.results_panel]
border_type = "rounded"
# padding = {"left": 0, "right": 0, "top": 0, "bottom": 0}

[ui.preview_panel]
# Preview panel size (percentage of screen width/height)
size = 50
#header = ""
#footer = ""
scrollbar = true
border_type = "rounded"
# padding = {"left": 0, "right": 0, "top": 0, "bottom": 0}
hidden = false

[ui.help_panel]
show_categories = true

[ui.remote_control]
show_channel_descriptions = true
sort_alphabetically = true

[keybindings]
esc = "quit"
ctrl-c = "quit"
down = "select_next_entry"
ctrl-n = "select_next_entry"
ctrl-j = "select_next_entry"
up = "select_prev_entry"
ctrl-p = "select_prev_entry"
ctrl-k = "select_prev_entry"

# History navigation
ctrl-up = "select_prev_history"
ctrl-down = "select_next_history"

# Multi-selection
tab = "toggle_selection_down"
backtab = "toggle_selection_up"
enter = "confirm_selection"

# Preview panel control
pagedown = "scroll_preview_half_page_down"
pageup = "scroll_preview_half_page_up"
ctrl-f = "cycle_previews"

# Data operations
ctrl-y = "copy_entry_to_clipboard"
ctrl-r = "reload_source"
ctrl-s = "cycle_sources"

# UI Features
ctrl-t = "toggle_remote_control"
ctrl-x = "toggle_action_picker"
ctrl-o = "toggle_preview"
ctrl-h = "toggle_help"
f12 = "toggle_status_bar"
ctrl-l = "toggle_layout"

# Input field actions
backspace = "delete_prev_char"
ctrl-w = "delete_prev_word"
ctrl-u = "delete_line"
delete = "delete_next_char"
left = "go_to_prev_char"
right = "go_to_next_char"
home = "go_to_input_start"
ctrl-a = "go_to_input_start"
end = "go_to_input_end"
ctrl-e = "go_to_input_end"
