[mgr]
show_hidden = true
sort_by = "natural"
sort_sensitive = false
sort_reverse = false
sort_dir_first = true
linemode = "none"

ratio = [3, 3, 3]

scrolloff = 8
mouse_events = ["click", "scroll"]

[preview]
wrap = "no"
tab_size = 4
max_width = 1200
max_height = 1800
cache_dir = ""

[opener]

edit = [{ run = 'nvim "$@"', block = true }]

reveal = [{ run = 'open -R "$1"' }]

play = [{ run = 'open "$@"', orphan = true }]

extract = [{ run = 'ouch decompress "$@"', block = true }]

compress = [{ run = 'ouch compress "$@"', block = true }]
