auto_sync = true
sync_frequency = "0"
search_mode = "daemon-fuzzy"

[sync]
records = true

search_mode = "fuzzy"
show_preview = true
exit_mode = "return-query"

style = "compact"
inline_height = 20
invert = false
show_help = true
update_check = false
keymap_mode = "auto"
command_chaining = true

[dotfiles]
enabled = true

[stats]
common_subcommands = [
  "cargo",
  "git",
  "go",
  "npm",
  "python",
  "rustup",
  "tmux",
  "uv",
  "zig",
]

common_prefix = ["sudo"]
ignored_commands = ["cd", "ls", "pwd", "clear", "reset"]

[ui]
columns = ["duration", "time", "command"]

[theme]
name = "catppuccin"

[ai]
enabled = true

[daemon]
enabled = true
autostart = true
