# ---- Environment Variables ----
# XDG 
export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
export XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
export XDG_CACHE_HOME="${XDG_CACHE_HOME:-$HOME/.cache}"

# Editor
export BAT_THEME="Catppuccin-mocha"
export EDITOR="${EDITOR:-nvim}"
export VISUAL="${VISUAL:-nvim}"
export PAGER="${PAGER:-bat}"
export MANPAGER="bat -l man -p"

# go
export GOROOT="/usr/local/go"
export GO111MODULE=auto
export GOPATH="$HOME/go"
export GOBIN=$HOME/go/bin
export GOTOOLCHAIN=local

# terminal
export COLORTERM=truecolor

