##=================================================##
#                                                   #
# Termbox bashrc file.                              #
#                                                   #
# contains bash config, alias and functions         #
# managed and owned by termbox                      #
#                                                   #
##=================================================##

# ── Termbox env ───────────────────────────────────────────────────────────────
source $HOME/.config/termbox/termbox.env

# ── Theming ───────────────────────────────────────────────────────────────────
if [[ -z "$TMUX" ]] && [[ "$SHLVL" -eq 1 ]]; then
    _tb_theme="$TERMBOX_DATA_DIR/themes/$THEME_NAME.theme"
    [ -f "$_tb_theme" ] && source "$_tb_theme"
    unset _tb_theme
fi

# ── Splash Screen ─────────────────────────────────────────────────────────────
if [[ -z "$TMUX" ]] && [[ "$SHLVL" -eq 1 ]] && [[ "${TERMBOX_SHOW_SCREEN:-true}" == "true" ]]; then
    command -v termbox &>/dev/null && termbox splash show 2>/dev/null
fi

